volumes:
  postgres_data:
  redis_data:

services:
  database:
    container_name: postgres_container
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    container_name: fastapi_container
    build: ../
    command: ["/wb/infra/app.sh"]
    depends_on:
      - database
    ports:
      - "80:8000"
    restart: always
    env_file:
      - .env

  bot:
    build: ../aiogram_app/
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "81:81"
    env_file:
        - .env
